service: ai-goal-visualizer

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 30
  memorySize: 512
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, 'dummy-openai-key'}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY, 'dummy-gemini-key'}

functions:
  app:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    strip: false
  customDomain:
    domainName: goals.teejaz.com
    certificateArn: arn:aws:acm:us-east-1:746323528772:certificate/5596e40f-b8d5-47e9-a7a2-ec6f65df9747
    createRoute53Record: false
    endpointType: 'regional'
