AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AIGoalVisualizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ai-goal-visualizer-deploy-1754331253.43707/deployment.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 256
      Timeout: 15
      Environment:
        Variables:
          OPENAI_API_KEY: dummy
          GEMINI_API_KEY: dummy
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"